---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: eirikns.apt
      vars:
        apt_additional_packages:
          - curl
        apt_autoremove: true
        apt_configure_unattended_upgrades: true
        apt_configure_periodic: true
