---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: eirikns.apt
      vars:
        apt_configure_unattended_upgrades: true
        apt_configure_periodic: true
        apt_unattended_upgrades_origins_extra:
          - "${distro_id}:${distro_codename}-updates"
          - "${distro_id}:${distro_codename}-backports"
        apt_unattended_upgrades_package_blocklist:
          - "linux-"
        apt_unattended_upgrades_automatic_reboot: false
        apt_unattended_upgrades_mail: "admin@example.com"
        apt_unattended_upgrades_mail_only_on_error: true
        apt_unattended_upgrades_dpkg_options:
          - "--force-confdef"
          - "--force-confold"
